version: "3.3"
services:
  mysql:
    image: mysql:latest
    ports:
      - "3307:3306"
    volumes:
      - ./database/initdb.d:/docker-entrypoint-initdb.d
      - ./database/data:/var/lib/mysql
    environment: 
      MYSQL_DATABASE: photos
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${USERPASS}
      MYSQL_ROOT_PASSWORD: ${ROOTPASS}
    container_name: localhost
